codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 80...90

  status:
    project:
      default:
        enabled: yes
        target: 1
        threshold: 0.1
    patch:
      default:
        enabled: off        
# ignore generation of tables and graphs in test coverage
ignore:
  - "src/Visualization.jl"
